# Generated by Django 4.2 on 2024-01-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScammerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('scammer_phone', models.CharField(max_length=20)),
                ('telecom_provider', models.CharField(choices=[('ais', 'AIS'), ('dtac', 'DTAC'), ('true', 'True')], default='ais', max_length=10)),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
